<%@ Page Title="" Language="C#" MasterPageFile="~/FrontOffice/MainMaster.master" AutoEventWireup="true" CodeFile="frm_RegisterComplain.aspx.cs" Inherits="Administrator_frm_RegisterComplain" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">

    <script src="<%# ResolveUrl("~/Content/js/jquery.signalR-2.2.2.min.js") %>"></script>
    <script type="text/javascript" src="http://localhost:9090/signalr/hubs"></script>   
    <script src="<%# ResolveUrl("~/Content/js/wheelzoom.js") %>" type="text/javascript"></script>

    <!--Reference the autogenerated SignalR hub script. -->
    <script>      

        $(document).ready(function () {
            $("[id*=chkdocument]").bind("click", function () {
                //Find and reference the GridView.
                var grid = $(this).closest("table");
                //If the CheckBox is Checked then enable the TextBoxes in thr Row.
                if (!$(this).is(":checked")) {
                    var td = $("td", $(this).closest("tr"));
                    //td.css({ "background-color": "#FFF" });
                    $("input[type=button]", td).attr("disabled", "disabled");
                } else {
                    var td = $("td", $(this).closest("tr"));
                    //td.css({ "background-color": "#D8EBF2" });
                    $("input[type=button]", td).removeAttr("disabled");
                }
            });
        });
        

        function Validate() {
            if ($('#<%=txtSearchRefNo.ClientID%>').val() == "" && ($('#<%=ddlSearchScheme.ClientID%>').val() == "0" || $('#<%=txtSearchPlotNo.ClientID%>').val() == "")) {
                $('#<%=lblmsg.ClientID%>').html("Please Select Reference No. OR Scheme AND PlotNo. ");
                return false;
            }
        }
      
        var rowindexGL='0';
        function getScannerImg(rowindex) {

            $('.loading').addClass('actives');

            debugger;
            rowindexGL=rowindex;
            //Set the hubs URL for the connection
            $.connection.hub.url = "http://localhost:9090/signalr";
            // Declare a proxy to reference the hub.
            var chat = $.connection.myHub;

            // Create a function that the hub can call to broadcast messages.
            chat.client.addMessage = function (name, message) {    
                if (name==1) {                  
                    var id = '#imgscan' + rowindexGL;
                    var hfid ='#ContentPlaceHolder1_grdDocuments_hdnimg_'+rowindexGL;
                    // console.log(message);
                    $(id).attr('src', 'data:image/png;base64,' + message);
                    $(hfid).val(message);
                    $('#ContentPlaceHolder1_grdDocuments_lblstatus_'+rowindexGL).html('true');
                    $('#ContentPlaceHolder1_grdDocuments_hdnStatus_'+rowindexGL).val(1);
                }
                else{
                    $('#ContentPlaceHolder1_grdDocuments_lblstatus_'+rowindexGL).html('false');
                    $('#ContentPlaceHolder1_grdDocuments_hdnStatus_'+rowindexGL).val(0);
                }
                setTimeout(function(){ $('.loading').removeClass('actives'); }, 10000);
               
            };

            var myVar;
            $.connection.hub.start().done(function () {
                var imgdata = chat.server.send(720,400);
                console.log(imgdata);

                // $('#message').val('').focus();
            });
            return false;
        }

        function myFunction(x)
        {
            $('#myModal').modal('show');
            $imgsrc=$('#imgscan'+x).attr('src');
            $('#ContentPlaceHolder1_imgdocs').attr("src",$imgsrc);

        }

        $(document).ready(function () {
            wheelzoom(document.querySelector('img.zoom'));
        });


        function SaveValidate() {           
            
            if($('#<%=ddlDepartment.ClientID%>').val() == "0" )
            {
                $('#<%=pnlfailed.ClientID%>').html("Please Select Department No. ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"});
                //$("p").css("display","block")
                $('#<%=pnlfailed.ClientID%>').addClass("alertMsg failed");
                return false;
            }
            if ($('#<%=txtPlotNo.ClientID%>').val() == "" ) {
                $('#<%=pnlfailed.ClientID%>').html("Please Enter Reference No. ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"})
                return false;
            }
            if ($('#<%=txtRefNo.ClientID%>').val() == "" ) {
                $('#<%=pnlfailed.ClientID%>').html("Please Enter Reference No. ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"})
                return false;
            }
            else if($('#<%=txtServiceNo.ClientID%>').val() == "" )
            {
                $('#<%=pnlfailed.ClientID%>').html("Please Enter Service No. ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"});
                return false;
            }
            else if($('#<%=ddlScheme.ClientID%>').val() == "0" )
            {
                $('#<%=pnlfailed.ClientID%>').html("Please Select Scheme ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"});
                return false;
            }
            else if($('#<%=ddlServices.ClientID%>').val() == "0" )
            {
                $('#<%=pnlfailed.ClientID%>').html("Please Select Services ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"});
                return false;
            }
            else if($('#<%=ddlMatter.ClientID%>').val() == "0" )
            {
                $('#<%=pnlfailed.ClientID%>').html("Please Select Matter ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"});
                return false;
            }
            <%--else if($('#<%=txtOtherRemark.ClientID%>').val() == "" )
            {
                $('#<%=pnlfailed.ClientID%>').html("Please Enter Other Remark. ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"});
                return false;
            }--%>
            else if($('#<%=txtComplainer.ClientID%>').val() == "" )
            {
                $('#<%=pnlfailed.ClientID%>').html("Please Enter Complainer Name. ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"});
                return false;
            } 
            else if($('#<%=txtMobileNo.ClientID%>').val() == "" )
            {
                $('#<%=pnlfailed.ClientID%>').html("Please Enter Mobile No. ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"});
                return false;
            }
            else if($('#<%=txtAadharNo.ClientID%>').val() == "" )
            {
                $('#<%=pnlfailed.ClientID%>').html("Please Enter Aadhar No. ");
                $('#<%=pnlfailed.ClientID%>').css({'display':"inline-block"});
                return false;
            }

}

    </script>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">


    <%--<asp:UpdatePanel ID="upl" runat="server">
        <ContentTemplate>--%>

    <div class="col-xs-12 col-sm-12">
        <div class="panel panel-primary register-complain-page">
            <div class="panel-heading">
                <h3 class="panel-title">Inward / Application </h3>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="panel-body form-horizontal">

                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Inward&nbsp;Type
                            </label>
                            <div class="col-xs-12 col-sm-12 ">
                                <asp:DropDownList runat="server" CssClass="form-control" ID="ddlInwardType" Enabled="false">
                                    <asp:ListItem Value="0">--Select Inward Type--</asp:ListItem>
                                </asp:DropDownList>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Department&nbsp;Name 
                            </label>
                            <div class="col-xs-12 col-sm-12">
                                <asp:DropDownList runat="server" CssClass="form-control" ID="ddlDepartment" AutoPostBack="true" OnSelectedIndexChanged="ddlDepartment_SelectedIndexChanged">
                                    <asp:ListItem Value="0">--Select Department Name--</asp:ListItem>
                                </asp:DropDownList>
                            </div>
                        </div>
                    </div>


                </div>

                <asp:UpdatePanel ID="upl" runat="server">
                    <ContentTemplate>
                <div class="row innr_pnl one">
                    <div class="col-xs-12 text-center search-by-cr-heading">
                        <b>Search By Basic Criteria </b>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="col-xs-12 col-sm-12">
                                Reference&nbsp;No.
                            </label>
                            <div class="col-xs-12 col-sm-12 ">
                                <asp:TextBox ID="txtSearchRefNo" runat="server" class="form-control" MaxLength="10"></asp:TextBox>
                                <ajaxToolkit:FilteredTextBoxExtender ID="fte1" runat="server" ValidChars="0123456789" TargetControlID="txtSearchRefNo" />
                                <span class="or-label">OR</span>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Scheme
                            </label>
                            <div class="col-xs-12 col-sm-12">
                                <asp:DropDownList runat="server" CssClass="form-control" ID="ddlSearchScheme">
                                    <asp:ListItem>--Select Scheme--</asp:ListItem>
                                </asp:DropDownList>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Plot No.
                            </label>
                            <div class="col-xs-12 col-sm-12 ">
                                <asp:TextBox ID="txtSearchPlotNo" runat="server" class="form-control" MaxLength="30"></asp:TextBox>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                &nbsp;
                            </label>
                            <div class="col-xs-12 col-sm-12 text-right">
                                <asp:Button ID="btnSearch" Text="Search" runat="server" ValidationGroup="a" CssClass="btn btn-success btn-xs btnSave" OnClientClick="return Validate();" OnClick="btnSearch_Click" />
                                <asp:Button ID="Button4" Text="Advance Search" runat="server" ValidationGroup="a" CssClass="btn btn-primary btn-xs btnSave" />
                                <asp:Button ID="btnSearchClear" Text="Clear" runat="server" CssClass="btn btn-default btn-xs btnClear" OnClick="btnSearchClear_Click" />
                            </div>
                            <asp:Label ID="lblmsg" CssClass="errorMsg" ForeColor="Red" runat="server"></asp:Label>
                        </div>
                    </div>

                </div>

                
                        <div class="row innr_pnl two" >
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="col-xs-12 col-sm-12">
                                        Reference&nbsp;No.
                                    </label>
                                    <div class="col-xs-12 col-sm-12 ">
                                        <asp:TextBox ID="txtRefNo" runat="server"  MaxLength="10"  CssClass="form-control" Enabled="false" ></asp:TextBox>
                                        <ajaxToolkit:FilteredTextBoxExtender ID="FilteredTextBoxExtender11" runat="server" ValidChars="0123456789" TargetControlID="txtRefNo" />

                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class=" col-xs-12 col-sm-12">
                                        Service No
                                    </label>
                                    <div class="col-xs-12 col-sm-12">
                                        <asp:TextBox ID="txtServiceNo" runat="server" CssClass="form-control" MaxLength="10" Enabled="false"></asp:TextBox>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class=" col-xs-12 col-sm-12">
                                        Plot No.
                                    </label>
                                    <div class="col-xs-12 col-sm-12 ">
                                        <asp:TextBox ID="txtPlotNo" runat="server" CssClass="form-control" Enabled="false"></asp:TextBox>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class=" col-xs-12 col-sm-12">
                                        Property&nbsp;Holder Name
                                    </label>
                                    <div class="col-xs-12 col-sm-12 ">
                                        <asp:TextBox ID="txtPropPlaceHolder" runat="server" CssClass="form-control" Enabled="false"></asp:TextBox>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class=" col-xs-12 col-sm-12">
                                        Address
                                    </label>
                                    <div class="col-xs-12 col-sm-12">
                                        <asp:TextBox ID="txtAddress" runat="server" CssClass="form-control" Enabled="false"></asp:TextBox>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class=" col-xs-12 col-sm-12">
                                        Scheme
                                    </label>
                                    <div class="col-xs-12 col-sm-12">
                                        <asp:DropDownList runat="server" CssClass="form-control" ID="ddlScheme" Enabled="false">
                                            <asp:ListItem>--Select Scheme--</asp:ListItem>
                                        </asp:DropDownList>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </ContentTemplate>
                </asp:UpdatePanel>

                <div class="row">

                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Services
                            </label>
                            <div class="col-xs-12 col-sm-12 ">
                                <asp:DropDownList runat="server" CssClass="form-control" ID="ddlServices" AutoPostBack="true" OnSelectedIndexChanged="ddlServices_SelectedIndexChanged">
                                    <asp:ListItem Value="0">--Select Service--</asp:ListItem>
                                </asp:DropDownList>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Enter Matter
                            </label>
                            <div class="col-xs-12 col-sm-12">
                                <asp:DropDownList runat="server" CssClass="form-control" ID="ddlMatter" AutoPostBack="true" OnSelectedIndexChanged="ddlMatter_SelectedIndexChanged">
                                    <asp:ListItem Value="0">--Select Matter--</asp:ListItem>
                                </asp:DropDownList>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Other&nbsp;Remark
                            </label>
                            <div class="col-xs-12 col-sm-12">
                                <asp:TextBox ID="txtOtherRemark" runat="server" class="form-control" MaxLength="200"></asp:TextBox>

                            </div>
                        </div>
                    </div>



                </div>


                <div class="row innr_pnl" id="pnldocuments" runat="server" style="display: none">
                    <div class="col-sm-12">
                        <div class="row">

                            <label class="col-xs-12 col-sm-3">
                                Required Document
                            </label>

                            <div class="col-sm-9 table-responsive">
                                <asp:GridView ID="grdDocuments" runat="server" AutoGenerateColumns="false" class="table table-bordered mb0" ShowHeader="false"
                                    EmptyDataText="No record found" Style="max-width: 628px">
                                    <Columns>
                                        <asp:TemplateField ItemStyle-Width="70%">
                                            <ItemTemplate>
                                                <asp:HiddenField ID="hdnDocumentcode" runat="server" Value='<%#Eval("DocumentCode") %>' />
                                                <asp:CheckBox ID="chkdocument" runat="server" Text='<%#Eval("DocumentNME") %>' />
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField ItemStyle-Width="10%">
                                            <ItemTemplate>
                                                <%--<asp:button ID="lnkUpdate" Text="Scan" runat="server" CssClass="btn btn-warning  btn-xs"  OnClientClick="return getScanner('"<%#Container.DataItemIndex %>"');" disabled="disabled"/>--%>
                                                <input type="button" id="lnkUpdate" value="Scan" class="btn btn-warning  btn-xs" onclick="getScannerImg('<%#Container.DataItemIndex%>    ');" disabled="disabled" />

                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField ItemStyle-Width="10%">
                                            <ItemTemplate>
                                                <img height="30" width="30" id="imgscan<%#Container.DataItemIndex%>" style="cursor: pointer" onclick="myFunction('<%#Container.DataItemIndex%>')" />
                                                <%--  <asp:Image ID="imgscan" runat="server" src="" Height="30px" Width="30px" style="cursor:pointer" onclick='myFunction(<%#Container.DataItemIndex%>)'></asp:Image>--%>
                                                <asp:HiddenField ID="hdnimg" runat="server" />
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField ItemStyle-Width="10%">
                                            <ItemTemplate>
                                                <asp:Label ID="lblstatus" runat="server" Text="Status" />
                                                <asp:HiddenField ID="hdnStatus" Value="0" runat="server" />
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                    </Columns>
                                </asp:GridView>

                            </div>
                        </div>
                    </div>

                </div>


                <div class="modal fade" id="myModal" role="dialog">
                    <div class="modal-dialog">

                        <div class="modal-content">
                            <div class="modal-body">
                                <asp:Image Class='zoom' ID="imgdocs" Height="400px" Width="570px" runat="server" />
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>

                    </div>
                </div>


                <div class="row bx">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Complainer Name
                            </label>
                            <div class="col-xs-12 col-sm-12 ">
                                <asp:TextBox ID="txtComplainer" runat="server" class="form-control" MaxLength="50"></asp:TextBox>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Mobile No.
                            </label>
                            <div class="col-xs-12 col-sm-12">
                                <asp:TextBox ID="txtMobileNo" runat="server" class="form-control" MaxLength="10"></asp:TextBox>
                                <ajaxToolkit:FilteredTextBoxExtender ID="FilteredTextBoxExtender123" runat="server" ValidChars="0123456789" TargetControlID="txtMobileNo" />
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Aadhar No.
                            </label>
                            <div class="col-xs-12 col-sm-12 ">
                                <asp:TextBox ID="txtAadharNo" runat="server" class="form-control" MaxLength="15"></asp:TextBox>
                                <ajaxToolkit:FilteredTextBoxExtender ID="FilteredTextBoxExtender124" runat="server" ValidChars="0123456789" TargetControlID="txtAadharNo" />
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class=" col-xs-12 col-sm-12">
                                Picture
                            </label>
                            <div class="col-xs-12 col-sm-12">
                                <asp:FileUpload ID="fuPicture" runat="server" class="form-control" />
                            </div>
                        </div>
                    </div>
                </div>


            </div>

            <div class="panel-footer text-right">
                <div class="alertMsg success" runat="server" id="pnlSuccess" style="display: none"></div>
                <div class="alertMsg failed" runat="server" id="pnlfailed" style="display: none"></div>
                <asp:Button ID="btnSave" Text="Save" runat="server" ValidationGroup="a" CssClass="btn btn-success btnSave" OnClientClick="return SaveValidate();" OnClick="btnSave_Click" />
                <asp:Button ID="btnClear" Text="Clear" runat="server" CssClass="btn btn-default btnClear" OnClick="btnClear_Click" />
                <asp:Button ID="btnExit" runat="server" PostBackUrl="~/FrontOffice/Dashboard.aspx" CssClass="btn btn-danger" Text="Exit" />

            </div>
        </div>
    </div>

    <%-- </ContentTemplate>
    </asp:UpdatePanel>--%>
</asp:Content>

